# -*- coding: utf-8 -*-
"""run.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwrGuAYYdUNhojQEfpzlshjUUH00_a0A
"""



import streamlit as st
import pickle
import numpy as np

# Load the trained model
with open("instagram_reach_model.pkl", "rb") as file:
    model = pickle.load(file)

st.title("Instagram Reach Predictor")

# User Inputs
from_home = st.number_input("From Home", min_value=0)
from_hashtags = st.number_input("From Hashtags", min_value=0)
from_explore = st.number_input("From Explore", min_value=0)
from_other = st.number_input("From Other", min_value=0)
saves = st.number_input("Saves", min_value=0)
comments = st.number_input("Comments", min_value=0)
shares = st.number_input("Shares", min_value=0)
likes = st.number_input("Likes", min_value=0)
profile_visits = st.number_input("Profile Visits", min_value=0)
follows = st.number_input("Follows", min_value=0)

# Predict Button
if st.button("Predict Reach"):
    input_data = np.array([[from_home, from_hashtags, from_explore, from_other,
                             saves, comments, shares, likes, profile_visits, follows]])

    predicted_impressions = model.predict(input_data)[0]
    st.success(f"Predicted Impressions: {int(predicted_impressions)}")

